[package]
name = "hyperlane-core"
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license-file.workspace = true
publish.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait.workspace = true
auto_impl = "1.0"
bytes = { version = "1", features = ["serde"]}
config.workspace = true
derive-new.workspace = true
ethers-providers.workspace = true
ethers-signers.workspace = true
ethers.workspace = true
hex = "0.4.3"
lazy_static = "*"
num = {version="0", features=["serde"]}
num-derive = "0.3"
num-traits = "0.2"
rocksdb.workspace = true
serde.workspace = true
serde_json.workspace = true
sha3 = "0.10"
strum = "0.24"
strum_macros = "0.24"
thiserror.workspace = true
tokio = { workspace = true, features = ["rt", "macros"] }
tracing-futures.workspace = true
tracing.workspace = true

# version determined by ethers-rs
primitive-types = "*"

[dev-dependencies]
hyperlane-base = { path = "../hyperlane-base" }
tokio = { workspace = true, features = ["rt", "time"] }
walkdir = { version = "2" }

[features]
output = []
