[package]
name = "hyperlane-ethereum"
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license-file.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
# Main block
async-trait.workspace = true
derive-new.workspace = true
ethers-contract.workspace = true
ethers-signers.workspace = true
ethers.workspace = true
hex = "0.4.3"
num = "0.4"
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing-futures.workspace = true
tracing.workspace = true
url = "2.3"

hyperlane-core = { path = "../../hyperlane-core" }
ethers-prometheus = { path = "../../ethers-prometheus", features = ["serde"] }

[build-dependencies]
abigen = { path = "../../utils/abigen", features = ["ethers"] }
