[package]
name = "migration"
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license-file.workspace = true
publish.workspace = true
version.workspace = true

[lib]
name = "migration"
path = "src/lib.rs"

[dependencies]
sea-orm = {version = "0.11.1", features = ["macros", "with-bigdecimal", "with-time"]}
sea-orm-migration = { version = "0.11.1", features = ["runtime-tokio-native-tls", "sqlx-postgres"] }
serde.workspace = true
time = "0.3"
tokio = { workspace = true, features = ["rt", "macros"] }

hyperlane-core = { path = "../../../hyperlane-core" }

# bin-only deps
tracing-subscriber.workspace = true
tracing.workspace = true

[[bin]]
name = "init-db"
path = "bin/init_db.rs"

[[bin]]
name = "recreate-db"
path = "bin/recreate_db.rs"

[[bin]]
name = "generate-entities"
path = "bin/generate_entities.rs"

[features]
default = []
